sqlfluff-lint:
    name: Lint SQL (SQLFluff)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install SQLFluff and dbt
        run: pip install sqlfluff sqlfluff-templater-dbt dbt-postgres

      - name: Copy profiles.yml
        run: |
          mkdir -p ~/.dbt
          cp spotify_dbt/profiles.yml ~/.dbt/profiles.yml

      - name: Install dbt packages
        working-directory: spotify_dbt
        run: dbt deps

      - name: Run SQLFluff lint
        working-directory: spotify_dbt
        run: |
          sqlfluff lint models/ \
            --dialect postgres \
            --templater dbt \
            --exclude-rules L031
        env:
          DBT_HOST: ${{ secrets.DBT_HOST }}
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
          DBT_DBNAME: ${{ secrets.DBT_DBNAME }}